---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
  annotations:
    force: "force-again"
spec:
  bindingRules:
    common: "true"
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    # SRIOV
    - fileName: SriovSubscription.yaml
      policyName: "sriov-sub-policy"
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-sub-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-sub-policy"
    # PTP
    - fileName: PtpSubscription.yaml
      policyName: "ptp-sub-policy"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "ptp-sub-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "ptp-sub-policy"
    # PAO 
    - fileName: PaoSubscription.yaml
      policyName: "pao-sub-policy"
      spec:
        source: redhat-operators
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-sub-policy"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-sub-policy"
#    - fileName: PaoSubscriptionCatalogSource.yaml
#      policyName: "pao-sub-policy"
#      spec:
#        image: quay.io/openshift-kni/performance-addon-operator-index:4.8-snapshot
    # CLO
#    - fileName: ClusterLogOperGroup.yaml
#      policyName: "log-sub-policy"
#    - fileName: ClusterLogSubscription.yaml
#      policyName: "log-sub-policy"
    # LSO
    - fileName: StorageNS.yaml
      policyName: "storage-sub-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "storage-sub-policy"
    - fileName: StorageSubscription.yaml
      policyName: "storage-sub-policy"
      spec:
        channel: "4.8"
    # Reduce Monitoring Operator Footprint
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "mon-offload-policy"
    # These CRs are in support of installation from a disconnected registry
#    - fileName: ClusterLogCatSource.yaml
#      policyName: "log-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-clo:latest
#    - fileName: PtpCatSource.yaml
#      policyName: "ptp-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-ptp:latest
#    - fileName: StorageCatSource.yaml
#      policyName: "storage-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-lso:latest
#    - fileName: SriovCatSource.yaml
#      policyName: "sriov-sub-policy"
#      spec:
#        image: registry.example.com:5000/olm/far-edge-sriov:latest
#    - fileName: DisconnectedICSP.yaml
#      policyName: "disc-icsp-policy"
#      spec:
#        repositoryDigestMirrors:
#        - mirrors:
#          - registry.redhat.com:5000
#          source: registry.redhat.io
#    - fileName: OperatorHub.yaml
#      policyName: "oper-hub-policy"

