---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "ztpclustera"
  namespace: "ztp-ztpclustera-policies"
spec:
  bindingRules:
    name: "ztpclustera"
  mcp: "master"
  remediationAction: inform
  sourceFiles: 
#    - fileName: MachineConfigOOTDriver.yaml

#    - fileName: MachineConfigOOTRealTimeKernel.yaml
#      policyName: "mc-oot-rtk-policy"
#    - fileName: MachineConfigOOTDriver.yaml 
#      policyName: "mc-oot-ice-policy"
#    - fileName: MachineConfigOOTDriver.yaml
#      policyName: "mc-oot-ice-ddp-policy"
#      metadata:
#        name: 11-ice-ddp-driver
#      spec:
#        #kernelArguments: -> added to PAO
#        #  - "firmware_class.path=/var/lib/firmware/"
#        config:
#          ignition:
#            version: 3.1.0
#          storage:
#            files:
#            - contents:
#                source: data:text/plain;charset=us-ascii;base64,IyEvYmluL2Jhc2gKCiMgVGhlIE1JVCBMaWNlbnNlCgojIENvcHlyaWdodCAoYykgMjAxOSBEdXN0eSBNYWJlCgojIFBlcm1pc3Npb24gaXMgaGVyZWJ5IGdyYW50ZWQsIGZyZWUgb2YgY2hhcmdlLCB0byBhbnkgcGVyc29uIG9idGFpbmluZyBhIGNvcHkKIyBvZiB0aGlzIHNvZnR3YXJlIGFuZCBhc3NvY2lhdGVkIGRvY3VtZW50YXRpb24gZmlsZXMgKHRoZSAiU29mdHdhcmUiKSwgdG8gZGVhbAojIGluIHRoZSBTb2Z0d2FyZSB3aXRob3V0IHJlc3RyaWN0aW9uLCBpbmNsdWRpbmcgd2l0aG91dCBsaW1pdGF0aW9uIHRoZSByaWdodHMKIyB0byB1c2UsIGNvcHksIG1vZGlmeSwgbWVyZ2UsIHB1Ymxpc2gsIGRpc3RyaWJ1dGUsIHN1YmxpY2Vuc2UsIGFuZC9vciBzZWxsCiMgY29waWVzIG9mIHRoZSBTb2Z0d2FyZSwgYW5kIHRvIHBlcm1pdCBwZXJzb25zIHRvIHdob20gdGhlIFNvZnR3YXJlIGlzCiMgZnVybmlzaGVkIHRvIGRvIHNvLCBzdWJqZWN0IHRvIHRoZSBmb2xsb3dpbmcgY29uZGl0aW9uczoKCiMgVGhlIGFib3ZlIGNvcHlyaWdodCBub3RpY2UgYW5kIHRoaXMgcGVybWlzc2lvbiBub3RpY2Ugc2hhbGwgYmUgaW5jbHVkZWQgaW4KIyBhbGwgY29waWVzIG9yIHN1YnN0YW50aWFsIHBvcnRpb25zIG9mIHRoZSBTb2Z0d2FyZS4KCiMgVEhFIFNPRlRXQVJFIElTIFBST1ZJREVEICJBUyBJUyIsIFdJVEhPVVQgV0FSUkFOVFkgT0YgQU5ZIEtJTkQsIEVYUFJFU1MgT1IKIyBJTVBMSUVELCBJTkNMVURJTkcgQlVUIE5PVCBMSU1JVEVEIFRPIFRIRSBXQVJSQU5USUVTIE9GIE1FUkNIQU5UQUJJTElUWSwKIyBGSVRORVNTIEZPUiBBIFBBUlRJQ1VMQVIgUFVSUE9TRSBBTkQgTk9OSU5GUklOR0VNRU5ULiBJTiBOTyBFVkVOVCBTSEFMTCBUSEUKIyBBVVRIT1JTIE9SIENPUFlSSUdIVCBIT0xERVJTIEJFIExJQUJMRSBGT1IgQU5ZIENMQUlNLCBEQU1BR0VTIE9SIE9USEVSCiMgTElBQklMSVRZLCBXSEVUSEVSIElOIEFOIEFDVElPTiBPRiBDT05UUkFDVCwgVE9SVCBPUiBPVEhFUldJU0UsIEFSSVNJTkcgRlJPTSwKIyBPVVQgT0YgT1IgSU4gQ09OTkVDVElPTiBXSVRIIFRIRSBTT0ZUV0FSRSBPUiBUSEUgVVNFIE9SIE9USEVSIERFQUxJTkdTIElOCiMgVEhFIFNPRlRXQVJFLgoKc2V0IC1ldQoKI0V4YW1wbGU6IGh0dHA6Ly9hcGFjaGU6ODA4MCBpY2VfY29tbXMtMS4zLjI4LjAucGtnIC92YXIvbGliL2Zpcm13YXJlL2ludGVsL2ljZS9kZHAKCkREUF9MT0NBVElPTl9CQVNFPSQxOyBzaGlmdApERFBfVkVSU0lPTj0kMTsgc2hpZnQKRldfRk9MREVSPSQxOyBzaGlmdAoKbG9nZ2VyICJkb3dubG9hZGluZyB0aGUgSW50ZWwgRERQIGZpbGVzIGZyb20gJHtERFBfTE9DQVRJT05fQkFTRX0vJEREUF9WRVJTSU9OIHRvICRGV19GT0xERVIgZm9sZGVyLi4uIgpjdXJsICR7RERQX0xPQ0FUSU9OX0JBU0V9LyR7RERQX1ZFUlNJT059IC0tb3V0cHV0ICR7RldfRk9MREVSfS9pY2UucGtnIHx8IGxvZ2dlciAiRERQIHBhY2thZ2UgZmFpbGVkIHRvIGRvd25sb2FkIgoKbW9kcHJvYmUgLXYgLXIgaWNlCgpzbGVlcCA1Cgptb2Rwcm9iZSAtdiBpY2UKCg==
#              filesystem: root
#              mode: 493
#              path: /usr/local/bin/ice-ddp-driver
#          systemd:
#            units:
#            - contents: |
#                [Unit]
#                Description=Update ddp for ice driver
#                # Start before the network is up and after /var is mounted
#                Wants=network-online.target
#                After=crio.service
#                Before=kubelet.service
#
#                [Service]
#                Type=oneshot
#                TimeoutStartSec=25m
#                RemainAfterExit=true
#                # Use bash to workaround https://github.com/coreos/rpm-ostree/issues/1936
#                ExecStart=/usr/bin/bash -c "/usr/local/bin/ice-ddp-driver http://10.19.138.94:8080 ice_comms-1.3.28.0.pkg /var/lib/firmware/intel/ice/ddp"
#                ExecStop=/usr/bin/bash -c "echo 1"
#                StandardOutput=journal+console
#
#                [Install]
#                WantedBy=default.target
#              enabled: true
#              name: ddp-ice-driver.service
#    - fileName: ClusterVersion.yaml
#      policyName: "cluster-lifecycle"
#      metadata:
#        name: "version"
#      spec:
#       channel: stable-4.9
#       clusterID: 2c0a1c32-dd31-4ee8-b983-2d84bbb557bd
#       desiredUpdate:
#         version: 4.8.14
#    - fileName: TunedPerformancePatch.yaml
#      policyName: "tuned-perf-patch-policy"
#      spec:
#        profile:
#          - name: performance-patch
#            data: |
#              [main]
#              summary=Configuration changes profile inherited from performance created tuned
#              include=openshift-node-performance-openshift-node-performance-profile
#              [bootloader]
#              cmdline_crash=nohz_full=2-15,18-19,22-23,26-31
#              [sysctl]
#              kernel.timer_migration=1
#              [service]
#              service.stalld=start,enable
